### ISSUE TITLE
在vue3.4.29 + ts 环境下，引入依赖后,dev运行正常，但build时报错，找不到longze-vue3-video-player依赖

### ISSUE THREAD

**Issue by kelvaer** [2441630833/npm_longze_vue3_video_player#1]
![image](https://github.com/2441630833/npm_longze_vue3_video_player/assets/161264733/17babc71-7b02-424d-861a-2813a06a3bb0)

error TS7016: Could not find a declaration file for module 'longze-vue3-video-player'. 'C:/dev/atd-search-web/node_modules/longze-vue3-video-player/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/longze-vue3-video-player` if it exists or add a new declaration (.d.ts) file containing `declare module 'longze-vue3-video-player';`

12 import longzeVideoPlay from "longze-vue3-video-player"; // 引入组件
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
transforming (1203) node_modules\@vue\reactivity\dist\reactivity.esm-bundler.jsERROR: "type-check" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 2441630833** [comment]
下的哪个版本？

**Comment by kelvaer** [comment]
"longze-vue3-video-player": "^1.1.5", 这个版本

**Comment by 2441630833** [comment]
package.json 文件里面有这个依赖吗，是不是没有save，你是用npm下载的还是yarn下载的呢？也有可能是缓存的问题，你可以把node_modules 删掉重新下载试试，我个人部署的项目build是没问题的，参考一下找不到npm项目依赖的链接：https://blog.csdn.net/sinat_33312523/article/details/76797501

**Comment by kelvaer** [comment]
找到解决办法了：
处理 Ts 导致的错误：新建一个与 main.ts 同级的文件 shims-vue.d.ts（如果不存在的话），并添加以下内容：

    /* eslint-disable */
    declare module '*.vue' {
      import type { DefineComponent } from 'vue'
      const component: DefineComponent<{}, {}, any>
      export default component
    }
    declare module 'longze-vue3-video-player'

**Comment by 2441630833** [comment]
嗯嗯，加一个模块类型声明就好了

**Comment by 2441630833** [comment]
你也可以pull request，我合并你的提交，感谢~

**Comment by kelvaer** [comment]
提了一个pull request 给你，你看看写的对不对

**Comment by 2441630833** [comment]
合并了，感谢~

**Comment by kelvaer** [comment]
那我关掉这个issues了

**Comment by 2441630833** [comment]
嗯嗯
