### ISSUE TITLE
speed参数一开始设置后，后面再更改不起作用。

### ISSUE THREAD

**Issue by 872301800** [2441630833/npm_longze_vue3_video_player#3]
有个需求。用户观看视频到一定时间才可以拖动滚动条。 一开始是禁止的。 后面需要放开。但是我看了源码，speed状态一开始从prop里面取值后。后面再更改 prop 的值不会起作用。 希望能添加此功能

**Comment by 872301800** [comment]
![1722310786481](https://github.com/user-attachments/assets/a9a0ed77-3fd9-4d57-963b-a349628bcfe9)
这里的值直接取prop里面的会不会好一点

**Comment by 872301800** [comment]
或者 state 直接定义为计算属性。应该也可以。

**Comment by 2441630833** [comment]
> 有个需求。用户观看视频到一定时间才可以拖动滚动条。 一开始是禁止的。 后面需要放开。但是我看了源码，speed状态一开始从prop里面取值后。后面再更改 prop 的值不会起作用。 希望能添加此功能

加了个方法，reversePropsSpeed，你直接调用就行了，videoRef.value.reversePropsSpeed(); 就会反转speed的值

**Comment by 2441630833** [comment]
你看看还有问题吗，可以的话把这个issue关了

**Comment by 872301800** [comment]
好的。没有了。 谢谢
